produits:
    path:     /
    defaults: { _controller: EcommerceBundle:Produits:produits }

presentation:
    path:     /produit/{id}
    defaults: { _controller: EcommerceBundle:Produits:presentation }

categories:
    path:     /categorie/{id}
    defaults: { _controller: EcommerceBundle:Produits:listing }

rechercheProduits:
    path:     /recherche
    defaults: { _controller: EcommerceBundle:Produits:rechercheTraitement }